name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Sincronizar archivos actualizados al servidor EC2
    - name: Sync files to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_SERVER }}
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Crear directorio si no existe
          mkdir -p ~/myapp

          # Sincronizar los archivos del proyecto (ajustar el directorio si es necesario)
          rsync -avz --delete ./ ubuntu@${{ secrets.EC2_SERVER }}:~/myapp/

    # 3. Reiniciar contenedores en EC2
    - name: Restart containers on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_SERVER }}
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Navegar al directorio del proyecto
          cd ~/myapp

          # Reiniciar contenedores con docker-compose
          sudo docker-compose down || true
          sudo docker-compose up -d

          # Verificar contenedores en ejecución
          sudo docker ps
