name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Loguearse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Construir y publicar la imagen Docker
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    # Conectarse al servidor EC2 y desplegar
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_SERVER }}
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Actualizar dependencias
          sudo apt update && sudo apt install -y docker.io docker-compose
          sudo systemctl enable --now docker

          # Crear directorio del proyecto
          mkdir -p ~/myapp

          # Crear archivo docker-compose.yml
          echo -e "
          version: '3.9'
          services:
            web:
              image: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
              container_name: myapp_container
              ports:
                - '80:80'
              restart: always
          " > ~/myapp/docker-compose.yml

          # Ir al directorio del proyecto
          cd ~/myapp

          # Detener contenedores existentes y desplegar los nuevos
          sudo docker-compose down || true
          sudo docker-compose up -d

          # Verificar contenedores en ejecución
          sudo docker ps
