name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Loguearse en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # 3. Construir y publicar la imagen Docker desde el código actual
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    # 4. Conectarse al servidor EC2 y ejecutar el despliegue
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_SERVER }}
        username: ubuntu
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Actualizar dependencias del servidor
          sudo apt update && sudo apt install -y docker.io docker-compose
          sudo systemctl enable --now docker

          # Crear directorio del proyecto si no existe
          sudo mkdir -p ~/myapp

          # Subir el archivo docker-compose.yml actualizado
          sudo echo -e "
          services:
            nginx:
              image: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
              container_name: nginx_server
              ports:
                - '80:80'
              restart: always
          " > ~/myapp/docker-compose.yml

          # Verificar el contenido del archivo docker-compose.yml
          sudo cat ~/myapp/docker-compose.yml

          # Descargar la última versión de la imagen desde Docker Hub
          cd ~/myapp
          sudo docker-compose pull

          # Detener cualquier contenedor en ejecución del proyecto actual
          sudo docker-compose down || true

          # Levantar el nuevo contenedor con docker-compose
          sudo docker-compose up -d

          # Verificar los contenedores en ejecución
          sudo docker ps

          # Verificar los logs del contenedor
          sudo docker logs nginx_server

          